# Usa una imagen oficial de Nginx como base
FROM nginx:alpine

# Copia los archivos del frontend al directorio de Nginx
COPY . /usr/share/nginx/html

# Expone el puerto 80
EXPOSE 80

# No es necesario definir CMD, ya que Nginx se ejecuta automáticamente
